# Generated by Django 3.1.5 on 2021-01-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud1Hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='unique_id',
            field=models.CharField(max_length=200),
        ),
    ]
